version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    volumes:
      - ssl-certs:/var/lib/https-portal
      - vhosts:/var/www/vhosts
    environment:
      DOMAINS: 'example.com -> http://wordpress'
    env_file: .env

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    ports:
      - '8000:80'
    depends_on:
      - db
    build: ./my-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
    volumes:
      # - ../wp_themes:/var/www/html/wp-content/themes
      - ../development/wp_themes/:/var/www/html/wp-content/themes/understrap-child-master
      - ../libs/wp_themes/understrap-master:/var/www/html/wp-content/themes/understrap-master
      - ../libs/wp_plugins:/var/www/html/wp-content/plugins

volumes:
  db_data:
    driver: local

  ssl-certs:
  vhosts:
