FROM wordpress:latest

# 必要なツール郡をインストール
RUN apt-get update
RUN apt-get -y install wget unzip

# WP プラグイン (zip) ダウンロード
WORKDIR /tmp/wp-plugins
RUN wget https://downloads.wordpress.org/plugin/contact-form-7.4.6.zip
RUN wget https://downloads.wordpress.org/plugin/syntaxhighlighter.zip
RUN wget https://downloads.wordpress.org/plugin/wp-emmet.zip
RUN wget https://downloads.wordpress.org/plugin/taxonomy-terms-order.1.5.4.zip
RUN wget https://downloads.wordpress.org/plugin/all-in-one-wp-migration.6.70.zip
RUN wget https://downloads.wordpress.org/plugin/wp-file-manager.zip

# Zip ファイルを解凍してインストール
RUN unzip './*.zip' -d /usr/src/wordpress/wp-content/plugins

# Install themes
WORKDIR /tmp/themes
RUN wget https://github.com/understrap/understrap/archive/master.zip
RUN wget -O child.zip https://github.com/understrap/understrap-child/archive/master.zip
RUN unzip './*.zip' -d /usr/src/wordpress/wp-content/themes


# 不要になった一時ファイルを削除
RUN apt-get clean
RUN rm -rf /tmp/*

# サーバが読めるように wp-content 以下の所有者を変更
RUN chown -R www-data:www-data /usr/src/wordpress/wp-content

WORKDIR /var/www/html
