version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    volumes:
      - ssl-certs:/var/lib/https-portal
      - vhosts:/var/www/vhosts
    environment:
      DOMAINS: 'example.com -> http://wordpress'
    env_file: .env

  mysql:
    image: mysql:5.7
    volumes:
      # - mysql_data:/var/lib/mysql
      - ../storages/mysql:/var/lib/mysql
    user: mysql
    restart: always
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    env_file: .env
    depends_on:
      - mysql
    links:
      - mysql
    ports:
       - '8080:80'
    volumes:
       - /sessions

  wordpress:
    ports:
      - '8000:80'
    depends_on:
      - mysql
    build: ./my-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
    env_file: .env
    volumes:
      # - ../wp_themes:/var/www/html/wp-content/themes
      - ../development/wp_themes/:/var/www/html/wp-content/themes/understrap-child-master
      - ../libs/wp_themes/understrap-master:/var/www/html/wp-content/themes/understrap-master

volumes:
  # mysql_data:
  ssl-certs:
  vhosts:
